name: app_base
description: My own commons library for flutter.
version: 0.2.0
author: DongYoon Kang <kdy1@outlook.kr>
homepage: https://github.com/kdy1/app_base

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  typed_firestore: ^0.0.2
  firebase_analytics: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

